votingworks/module-scan

src/endToEnd.test.ts
src/exec.test.ts
src/exec.ts
src/interpreter.ts
src/scanner.test.ts
src/scanner.ts

`exec` is vulnerable to command injection, i.e. if someone manages to control the parameters they can execute arbitrary code on the system. It's best avoided altogether, in my opinion.

refactor: use `execFile` instead of `exec`

---

Makefile
README.md

The tests were failing on a fresh clone because `zbarimg` was not installed and the code invoking it essentially ignores the error.
https://github.com/votingworks/module-scan/blob/5287a71a63ddfa17987cdf611cbf47e0cd01cf8e/src/interpreter.ts#L98-L102
This binary is provided by the `zbar` package on macOS (via Homebrew) or `zbar-tools` on Ubuntu. This commit updates the README to include instructions for installing `zbarimg`, which fixes the tests.
Fixes https://github.com/votingworks/module-scan/issues/21

docs: add instructions to install zbarimg

---

package.json
yarn.lock

Adding the `--files` flag to `ts-node` tells it to use the `files`, `include`, and `exclude` options in the `tsconfig.json` file. It doesn't do this by default, apparently for performance reasons (https://github.com/TypeStrong/ts-node#help-my-types-are-missing). This was not the recommended fix from `ts-node`'s README, but it seemed the least-impact approach.

fix: ensure `yarn start` works properly

---

package.json
yarn.lock

Since https://github.com/kAworu/node-quirc/pull/10 was merged and released in v2.1.0, we can replace our fork with the published version.

refactor: use published version of node-quirc

---

src/scanner.ts

When we were using `exec`, we had quotes around `ADF Duplex` to ensure that the shell grouped it as part of a single argument. However, the quotes were not part of the argument actually passed to `scanimage`. We can simply remove the quotes since we're passing the arguments exactly as we mean for them to be passed.

fix: ensure duplex scanning works

---

src/importer.ts

Rather than simply letting a promise rejection go unhandled, which in some later version of node will crash the process, we now bubble errors up and log them.

fix: log to stderr when an import fails

---

src/endToEnd.test.ts
src/importer.ts
src/interpreter.ts
src/types.ts

Now we no longer require going through v0 ballot encoding to generate CVRs.

refactor: build CVRs directly from a completed ballot

---

package.json

Removes this warning when committing:
```
Some of your tasks use `git add` command. Please remove it from the config since all modifications made by tasks will be automatically added to the git commit index.
```

build: remove unnecessary `git add` from lint-staged config

---

package.json
yarn.lock

This was fixed in the underlying library, just needed an update here.

fix: ignore black borders around the scanned image

---

README.md
index.html
jest.config.js
package.json
src/endToEnd.test.ts
src/endToEndHmpb.test.ts
src/importer.test.ts
src/importer.ts
src/interpreter.ts
src/server.test.ts
src/server.ts
src/store.test.ts
src/store.ts
test/util/mocks.ts
yarn.lock

- moved all config to `/config` endpoint
- fixed an issue with the database being destroyed on startup
- recreates the underlying interpreter on toggling test mode
- moves reloading of configuration out of `start` to allow it to be called on test mode toggle

feat: add test mode

---

src/interpreter.ts
types/node-quirc.d.ts

Sometimes quirc will find a QR code but be unable to decode it (e.g. an "ECC failure"). When this happens, an entry in the returned list is still created but it has a different structure. This commit updates the types to match the reality of what could be returned.
https://github.com/dlbeer/quirc/blob/c89d949371f5f0fd8546d5263e930938a0f84b8b/lib/decode.c#L333

fix: detect quirc decode errors

---

package.json
yarn.lock

This fixes [an issue](https://github.com/votingworks/hmpb-interpreter/pull/49) where it failed to interpret scanned images that had a black border that was larger than anticipated.

fix: update hmpb-interpreter

---

src/server.test.ts
src/store.test.ts
src/store.ts
src/types.ts
src/types/ballot-review.ts
src/util/applyChangesToMarks.test.ts
src/util/applyChangesToMarks.ts

BREAKING CHANGE. Rather than using true/false/undefined to mean marked/unmarked/marginal, we now use an enum with those values.

refactor: clarify values for mark status

---

.eslintrc.js
package.json
src/server.test.ts
yarn.lock

I had added an `.only` to run a specific test, but accidentally left it in. This removes the `.only`, fixes the tests that were failing silently in this file, and enables the recommended jest eslint rules (such as the one preventing the use of `.only`).

test: remove accidental focused test

---

index.html
src/importer.ts
src/interpreter.test.ts
src/interpreter.ts
src/server.test.ts
src/server.ts
test/util/mocks.ts

In development it's sometimes useful to scan from arbitrary files on disk. This allows using the test page to do that. It also removes the "Configure" functionality since that doesn't work with HMPB config anyway.

feat: allow scanning ballot images from files

---

src/server.ts
src/store.ts
src/types/ballot-review.ts

This adds a db column to keep track of whether a ballot requires adjudication, and an endpoint to get the ballot information for the next ballot requiring adjudication.
Refs votingworks/vxmail#19

feat: track which ballots require adjudication

---

index.html
src/server.ts

There were two bugs here:
- The test page only uploads a file when the input changes, and selecting the same file does not change it. I had tried to fix that, but did it incorrectly. Setting the file input value to `null` fixes it.
- We place imported files into a particular directory and name them based on the original filename. If you upload the same file twice, it would have the same destination file path. The unique constraint on `ballots#filename` in the database means the import fails. Now, we prepend the batch number to the filename to ensure it's unique.

fix: ensure manually uploading the same ballot for testing twice works

---

src/importer.ts
src/interpreter.test.ts
src/interpreter.ts

This is just a defensive move that makes it relatively easy to see, on audit, if two files are the same. We'll want to expand this later if we think it's a good thing to do.

fix: add a hash to imported filenames

---

src/util/marks.test.ts
src/util/marks.ts

fixes https://github.com/votingworks/vxmail/issues/123

bugfix: keep old contests around when merging adjudication

---

src/endToEndHmpb.test.ts
src/importer.test.ts
src/importer.ts

The tests have been hanging on finish for a while while jest waits for the child processes running the tests after their last test completes. It results in this warning:
> Jest did not exit one second after the test run has completed.
>
> This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
There were two causes:
- a file watcher that wasn't closed because there wasn't a matching `Importer#unconfigure` for every `Importer#configure`, leaving a file watcher in place
- a `setTimeout` used to finish the current batch had yet to fire
I fixed the first one by ensuring `unconfigure` was called properly. The second I fixed by clearing timeouts on unconfigure.

test: fix hang on finish

---

src/endToEndHmpb.test.ts
src/importer.ts
test/util/mocks.ts

This can be used to make the tests run more predictably, and could potentially be used by an HTTP endpoint.

feat: allow waiting for imports

---

package.json
src/store.ts
src/types/ballot-review.ts
src/util/allContestOptions.ts
src/util/ballotAdjudicationReasons.test.ts
src/util/ballotAdjudicationReasons.ts
yarn.lock

In addition to marginal marks, this commit adds support for detecting overvote, undervote, and write-in conditions. It currently does not act on them except to log the adjudication reason and that it was ignored. These will not be ignored in the future, and will be configurable by the end user at some point.
For example, uploading this file:
Logs this:
```
module-scan:store Adjudication reason ignored by configuration: Contest '4' has a write-in. +923ms
module-scan:store Adjudication reason ignored by configuration: Contest 'initiative-65' is overvoted, expected 1 but got 2: 'yes', 'no'. +0ms
```

feat: detect more adjudication conditions

---

package.json
src/importer.ts
src/server.test.ts
src/server.ts
src/store.ts
src/types.ts
src/util/ballotAdjudicationReasons.test.ts
src/util/ballotAdjudicationReasons.ts
yarn.lock

This also allows an election config to specify which adjudication reasons to use.

Detect blank ballots as a possible adjudication reason

---

src/endToEnd.test.ts
src/store.ts

address race condition in ballot creation that, when two ballots are added almost simultaneously, could return the same ballot ID in both cases. This was not likely to be a big problem because the two rows are still inserted, but now that I'm trying to use the return value, it matters.

race condition in ballot addition that could result in wrong return value for ballot ID

---

src/interpreter.ts

There's no reason at the moment to have a normalized image for BMD ballot scans. This saves about 500-800ms per BMD ballot scanned.

perf: do not re-encode BMD ballot scans

---

.github/workflows/ci.yml

Maybe it won't have this issue? https://github.com/facebook/jest/issues/8769
Not sure why, but it appears to pass (at least the one time). I think there really is an underlying issue, but I'm going to try to use GHA instead of CircleCI as the "required to merge" CI build for now, but keep running both.

test(ci): try Github Actions for CI

---

src/store.ts

The sqlite `CURRENT_TIMESTAMP` value is a string in ISO 8601 format, but without the timezone.

fix: add UTC suffix to timestamps

---

.gitignore
Makefile

Includes everything in the `tmp` directory where the images are stored, the database file, and the git revision.

chore: add Make target for dumping debug data

---

.gitignore
Makefile
schema.sql
src/importer.ts
src/server.ts
src/store.test.ts
src/store.ts

Changes are detected by creating a digest of the SQL file used to initialize the database. If it matches the `.digest` file associated with a database, it'll open and use the database as normal. If not, either because the digest file does not exist or because the value is different, the existing database will be backed up and a new one created in its place.

fix: re-create database if schema has changed

---

jest.config.js
package.json
src/interpreter.ts
src/store.ts
src/util/allContestOptions.ts
src/util/ballotAdjudicationReasons.ts
src/util/marks.ts
yarn.lock

This mostly incorporates the new contest type `ms-either-neither` while also being more explicit about what contest types we handle. For now, just fail on anything not `candidate` or `yesno`.

fix: upgrade election types

---

jest.config.js
src/endToEnd.test.ts
src/importer.test.ts
src/importer.ts
src/interpreter.ts
src/server.test.ts
src/server.ts
test/util/mocks.ts

We no longer need this, and it's going to be annoying to preserve it in a world where we interpret one sheet at a time.

refactor: remove manual ballots

---

src/importer.test.ts
src/importer.ts
src/server.ts

This simplifies the importer API.

refactor: use the file system for all imports

---

schema.sql
src/endToEnd.test.ts
src/importer.test.ts
src/importer.ts
src/interpreter.test.ts
src/interpreter.ts
src/server.test.ts
src/server.ts
src/store.test.ts
src/store.ts
src/types.ts
src/util/makeTemporaryBallotImportImageDirectories.ts
test/fixtures/emptyImage.ts

Previously we had a lot of cases where we ignored the results of importing a file. Now, we pull in all of them and keep track of how it failed.

feat: record an interpretation for every page

---

.gitignore
schema.sql
src/interpreter.test.ts
src/interpreter.ts
src/server.test.ts
src/store.test.ts
src/store.ts
src/types/ballot-review.ts

This moves the initial code to determine whether adjudication is required out of `Store` and into `Interpreter`, which feels better.

refactor: consolidate adjudication into page interpretation

---

package.json
schema.sql
src/buildCastVoteRecord.test.ts
src/buildCastVoteRecord.ts
src/importer.test.ts
src/importer.ts
src/interpreter.test.ts
src/interpreter.ts
src/server.test.ts
src/server.ts
src/store.test.ts
src/store.ts
src/types.ts
src/util/electionDefinition.ts
src/util/getBallotPageContests.test.ts
test/fixtures/2020-choctaw/ballot-p1-metadata.json
test/fixtures/2020-choctaw/ballot-p2-metadata.json
test/fixtures/state-of-hamilton/filled-in-dual-language-p1-metadata.json
test/fixtures/state-of-hamilton/filled-in-dual-language-p2-metadata.json
test/fixtures/state-of-hamilton/filled-in-dual-language-p3-metadata.json
test/fixtures/state-of-hamilton/filled-in-dual-language-p4-metadata.json
test/fixtures/state-of-hamilton/filled-in-dual-language-p5-metadata.json
yarn.lock

This updates hmpb-interpreter and ballot-encoder to support reading sheets with binary QR codes.

feat: read binary QR codes

---

src/interpreter.test.ts
src/interpreter.ts

Type annotations allow TS & the language server to provide IntelliSense suggestions in supported editors for the properties and their types. If you leave them off of a variable declaration where you're building up an object expression manually, TS cannot really help you. Likewise, [casting may allow you to create an object that is "close enough" to correct but not actually conform to the type][1], whereas a [type annotation will force you to correctly build the object][2].
[1]: https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgILIN4Chm+XALmRAFcBbAI2hzwqIGcwpQBzLAXyywQHsRHkPZAF5M+IgGZk7fPTTc+9HgBsIAOmU8WACjABPAA4QeMQWooBKIA
[2]: https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgILIN4Chm+XALmRAFcBbAI2hzwqIGcwpQBzLAXyywQHsRHkPIugC8mfEQDMyTr348ANhAB0CniwAUYAJ4AHCDxiDlFAJR …

style: use type annotations rather than casting

---

src/importer.ts
src/server.ts

The underlying interpreter is taught how to read the templates either when a new ballot package is uploaded or on startup when loading template information from the database. When switching test/live mode, the interpreter was recreated but _without teaching it about the templates_. Therefore, no matter what it was given, it would always throw "Cannot scan ballot because not all required templates have been added". That is, every `interpretBallot` call would fail.
To fix this issue, this commit restores the config from the database after switching test mode. Because this takes a non-trivial amount of time, we need to update bsd to tell the user what's happening.
Closes votingworks/vxmail#230

fix: ensure switching between test/live mode works

---

src/interpreter.test.ts
src/interpreter.ts

Your WIP PR is clearly the right way to go long-term, with rethinking how the data needs to be merged. For now, though, this feels like a safer and simpler change. Also, turns out we had the data we needed in here, the `marks` array, to determine if it's an intentionally blank page.

blank ballot determination adapted to intentionally blank pages

---

src/importer.ts
src/interpreter.ts
test/fixtures/choctaw-2020-09-22-02f807b005/fixtures.ts
test/util/mocks.ts

This fixes an issue where changing an election would cause all future scans to fail until the process was restarted.

fix: clear current election from memory on change

---

src/endToEndHmpb.test.ts
src/interpreter.ts

This enables scanning letter size in legal mode for BMD ballots, without changing the logic that determines paper orientation.

clip a larger portion of the image

---

src/scanner.ts

Smaller images are processed much faster, and 200dpi doesn't appear to reduce our ability to find QR codes.

scan at 200dpi

---

election.json
jest.config.js
src/endToEnd.test.ts
src/endToEndHmpb.test.ts
src/importer.test.ts
src/importer.ts
src/interpreter.test.ts
src/interpreter.ts
src/server.ts
src/store.test.ts
src/store.ts
src/workers/child-process-worker.js
src/workers/echo.ts
src/workers/interpret.ts
src/workers/pool.test.ts
src/workers/pool.ts
src/workers/worker-thread-worker.js
test/fixtures/state-of-hamilton/election.json
test/util/mocks.ts

Wraps `SummaryBallotInterpreter` in a worker interface that can run in a separate process. This allows us to interpret both sides at once with two child processes. I built `WorkerPool` in such a way that it supports various modes of operation (worker threads, child processes, inline), but am only using child processes in production. For tests, inline has been useful.
Why not worker threads? Mostly because any native dependencies used must adhere to some rules. In short: there are multiple C etc APIs for NodeJS extensions, and not all of them support being loaded in a thread.

perf: interpret both sides of a sheet in parallel

---

src/importer.test.ts
src/importer.ts

This mostly (but not completely) solves the problem if starting the scanning process before the configuration has been loaded by the worker processes. The error is now handled.

on error in importing, properly clean up the scanning process.

---

src/interpreter.ts
src/util/optionMarkStatus.test.ts
src/util/optionMarkStatus.ts

This wasn't working before because of the mismatch between inner and outer contest IDs.
This may hint at a larger refactor for either-neither in the future. For now, making a change that is minimal and contained.

fix adjudication for either-neither contests.

---

.eslintrc.js
src/interpreter.ts
src/util/perf.test.ts
src/util/perf.ts
src/util/qrcode.ts

zbarimg (via qrdetect) and quirc (via node-quirc) are both fairly fast QR code readers, but calling into node-quirc requires passing either JPEG or PNG data. We can and should fix that in the future, but for now it means a fairly heavy penalty (O(100ms)) for its use. So now we check both the top and bottom using qrdetect first (O(10ms)), and fall back to node-quirc if we can't find the QR code.
Additionally, we can save a little bit of time by checking the most likely half first. We hypothesize that EOs will put the paper in so that it looks right-side up to them, which means upside-down for the scanner. So we check the "top" first to find a QR code in the bottom of an upside-down HMPB image.
Both of these changes even out the time it takes with either orientation to be about the same, …

fix(perf): make QR code detection faster

---

README.md
bin/restore-backup
src/store.ts

This script can be used to restore an election backup file for local viewing or rescanning.
Example output:
```
Extracting database…
Archive:  /home/brian/Desktop/choctaw-10132020-special-runoff-backup.zip
inflating: ballots.db              
Success! Your backup has been restored.
Restart module-scan/bsd to see the changes.
To scan using the restored images, run this then restart module-scan/bsd in the same terminal:
$ export MOCK_SCANNER_FILES=@/home/brian/Desktop/choctaw-10132020-special-runoff-backup/manifest
```

feat: add restore script

---

package.json
src/cli/render-pages.test.ts
src/cli/render-pages.ts
src/importer.ts
src/interpreter.ts
src/store.ts
src/util/images.ts
src/util/qrcode.ts
test/util/mocks.ts
yarn.lock

Probably this: https://github.com/lovell/sharp/issues/1803. Tried pngjs (not compatible enough), jimp (too slow), and finally back to canvas which we've used before. It is a native dependency but doesn't seem to have the particular pathological behavior that sharp does while loading blank pages repeatedly.

fix: prevent sharp-related memory leak

---

src/importer.ts

Otherwise local development becomes a game of whack-a-mole with that file.

fix: restore `tmp/.gitkeep` on factory reset
