index.html, src/server.test.ts, src/server.ts
a simple page to test the API manually
=> Added test HTML page

src/endToEnd.test.ts, src/interpreter.ts, src/scanner.ts, src/server.test.ts, src/server.ts
make it possible to manually add a ballot via the API.
=> add manual scanning

package.json, src/endToEnd.test.ts, src/exec.ts, src/scanner.test.ts, src/scanner.ts, src/server.test.ts, src/server.ts, src/store.ts, yarn.lock
This also improves the types of some of the functions in `store.ts`.
=> style: use async/await instead of explicit promises

src/endToEnd.test.ts, src/importer.ts, src/interpreter.ts, src/types.ts
This also changes `_serialNumber` to `_ballotId`.
=> feat: add ballot style ID to CVRs

src/importer.ts, src/zbarimg.ts
- Use a `Set` for what sets are good for, i.e. tracking sets of things.
- Remove extra `return` statements.
=> refactor: minor improvements

src/importer.ts, src/interpreter.ts
This helps us add a different interpreter.
Note the extra function `interpretBallotData` can probably go as we've removed the "add manual ballot" UX in the scanner. I'm game to remove it in a next PR.
=> added interface for the interpreter

package.json, src/interpreter.ts, yarn.lock
This way we don't have to shell out.
=> refactor: use zbar from `@votingworks/qrdetect`

.circleci/config.yml, .eslintignore, .gitignore, jest.config.js
The thresholds chosen are the rounded-down value of the current coverage values.
=> test(coverage): set minimum coverage threshold

package.json, yarn.lock
Gets rid of some warnings from ts-jest.
=> build(dev-deps): update dependencies

src/endToEndHmpb.test.ts, src/interpreter.ts, src/types.ts
=> feat: record test ballot info in CVRs

src/endToEndHmpb.test.ts, src/interpreter.ts, src/types.ts, src/util/machineId.test.ts, src/util/machineId.ts
Refs https://github.com/votingworks/vxmail/issues/30
=> feat: encode machine ID in CVRs

jest.config.js, package.json, src/importer.ts, src/interpreter.test.ts, src/interpreter.ts, src/server.test.ts, src/server.ts, src/store.ts, src/types.ts, yarn.lock
This is a work-in-progress and shows the general approach I'm taking. Requires https://github.com/votingworks/hmpb-interpreter/pull/37
=> feat: add browsing of batches and ballots

package.json, yarn.lock
Incorporates votingworks/hmpb-interpreter#38 and votingworks/hmpb-interpreter#39.
=> fix: improve detection of target ovals

src/endToEndHmpb.test.ts, src/interpreter.test.ts, src/interpreter.ts
=> feat: include page number and locales in HMBP CVRs

src/endToEndHmpb.test.ts, src/interpreter.test.ts, src/interpreter.ts
=> fix: include only contests from the scanned page in the HMPB CVR

src/endToEndHmpb.test.ts
There was a logical merge conflict from two PRs that needed reconciling.
=> test: update snapshots

src/types.ts
I had changed this to 0.5 for testing and accidentally committed it.
=> fix: use the previous lower threshold

index.html
Without this, uploading the same file without reloading the page does not work.
=> fix: clear file input after upload

src/endToEnd.test.ts, src/endToEndHmpb.test.ts, src/importer.ts, src/interpreter.test.ts, src/interpreter.ts, src/server.test.ts, src/server.ts, src/store.test.ts, src/store.ts, test/fixtures/emptyImage.ts
This will pave the way for storing the information and adjudicating it.
=> feat: return metadata for uninterpretable HMPB ballots

src/importer.ts
This also makes the methods that add a ballot return the ballot id.
=> fix: await async actions correctly

Makefile
@eventualbuddha - Please update this with anything that you'd like to add more clarity. Feel free to merge as well.
=> docs: add install troubleshooting section.

package.json, src/interpreter.ts, src/scanner.ts, yarn.lock
This attempts to crop in a way that works for both BMD and HMPB. This does seem to work quite a bit more often, I will add tests to confirm this.
=> crop page to look for QR code in the right places

src/scanner.ts
this is pretty great when it works, but occasionally it seems to hang the scanning process, so let's not do that.
=> don't swcrop after all.

.eslintrc.js, src/store.ts, src/util/marks.ts, types/node-quirc.d.ts
=> test: report unused eslint disable directives

package.json, yarn.lock
This includes fixes to minimize false marginal marks.
=> fix: update hmpb-intepreter

src/store.ts
This mainly means we can let the database handle cascading deletes of batches onto ballots, but it also will prevent us from having dangling references to other tables.
=> fix: enforce db foreign key constraints

jest.config.js, schema.sql, src/LoopScanner.ts, src/buildCastVoteRecord.test.ts, src/buildCastVoteRecord.ts, src/endToEnd.test.ts, src/endToEndHmpb.test.ts, src/importer.test.ts, src/importer.ts, src/interpreter.test.ts, src/interpreter.ts, src/scanner.test.ts, src/scanner.ts, src/server.test.ts, src/server.ts, src/store.test.ts, src/store.ts, src/types.ts, src/util/marks.test.ts, src/util/marks.ts, test/util/mocks.ts
This ended up being a massive amount of changes to make at once, unfortunately. There's still some cleanup to do, but I think this works alright.
Closes votingworks/vxmail#168
Refs votingworks/vxmail#202
Refs votingworks/vxmail#184
=> feat: stitch together front & back of sheets

.eslintrc.js, package.json, src/backup.test.ts, src/backup.ts, src/server.ts, src/store.ts, types/compress-commons.d.ts, types/zip-stream.d.ts, yarn.lock
This allows us to export the database, the scanned images, the election config, and the current CVRs.
=> feat: add backup endpoint at `/scan/backup`

package.json, src/importer.test.ts, src/importer.ts, src/interpreter.test.ts, src/server.ts, yarn.lock
add ability to override the ballot ejection so overvotes and such can be recorded as such if they're true overvotes.
=> override ballot ejection for true overvotes etc.

src/importer.test.ts, src/server.test.ts, src/store.ts, src/util/ballotAdjudicationReasons.ts
=> feat: include interpretations in sheet adjudication endpoint

package.json, src/importer.test.ts, src/server.test.ts, yarn.lock
Includes votingworks/hmpb-interpreter#78 and votingworks/hmpb-interpreter#79.
=> Upgrade hmpb-interpreter

package.json, src/interpreter.test.ts, yarn.lock
@eventualbuddha I think one of the end-to-end tests is running forever on the bump. I'll look again soon.
=> better corners 2

.gitignore, README.md, src/LoopScanner.test.ts, src/LoopScanner.ts, src/index.ts, src/types.ts
I've been using this to re-scan large image dumps with algorithm tweaks.
=> feat: make it easier to mock scan large numbers of files

package.json, yarn.lock
Incorporates https://github.com/votingworks/hmpb-interpreter/pull/96.
=> fix: use all contest corners on 2-column pages

package.json, src/interpreter.test.ts, yarn.lock
https://github.com/votingworks/hmpb-interpreter/pull/100
=> fix: more more more corners

package.json, src/endToEndHmpb.test.ts, src/interpreter.test.ts, yarn.lock
https://github.com/votingworks/hmpb-interpreter/pull/97
=> fix: incorporate better scores
